name: prime-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=2.0.2
  - scipy=1.13.1
  - lightgbm=4.6.0
  - pandas>=2.1,<2.3
  - scikit-learn>=1.4,<1.7
  - joblib>=1.2
  - pyarrow>=14,<18
  - fastparquet>=2023.4
  - python>=3.9,<3.12
  - libxml2
