name: prime-env-numpy1
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - numpy=1.26
  - scipy=1.11
  - lightgbm=4.1
  - pandas>=2.1,<2.3
  - scikit-learn>=1.3,<1.5
  - joblib>=1.2
  - pyarrow>=14,<18
  - fastparquet>=2023.4
  - libxml2
