#' Run a Python Script for Profile Prediction
#'
#' This function runs a specified Python script using the `reticulate` package.
#'
#' @param script_path Character. The path to the Python script to be executed.
#' @param script_dir Character. The directory where the Python script resides.
#' @param profile_main_dir Character.
#' The main directory containing profile data.
#' @param profile_sub_dir Character.
#' The subdirectory within the main profile directory.
#' @param model_path Character.
#' The path to the trained model file to be used for prediction.
#' @param name_prefix Character.
#' A prefix to be added to the output files generated by the Python script.
#' @param threshold Numeric.
#' The probability threshold for classifying predictions. Default is 0.5.
#' @param file_format Character.
#' The format of the profile files (e.g., "parquet", "csv").
#' Default is "parquet".
#'
#' @return None. This function is used for its side effects of
#' running the Python script.
#'
#' @details
#' The function first checks if the specified Python script exists.
#' If the script exists, it constructs a command string to pass
#' the required arguments and runs the script using `reticulate::py_run_string`.
#' The command includes various parameters like the working directory,
#' profile directories, model path,
#' output name prefix, classification threshold, and file format.
#'
#' If the script does not exist, the function stops and throws an error message.
#'
#' @importFrom reticulate py_run_string
#'
#' @examples
#' \dontrun{
#' run_prediction_python_script(
#'   script_path = "path/to/predict_profile_probabilities.py",
#'   script_dir = "path/to/scripts",
#'   profile_main_dir = "path/to/profiles/main",
#'   profile_sub_dir = "subdir_name",
#'   model_path = "path/to/model.h5",
#'   name_prefix = "output_prefix",
#'   threshold = 0.7,
#'   file_format = "parquet"
#' )
#' }
#'
run_prediction_python_script <- function(script_path,
                                         script_dir,
                                         profile_main_dir,
                                         profile_sub_dir,
                                         model_path, name_prefix,
                                         threshold = 0.5,
                                         file_format = "parquet") {
  # Check if the script exists
  if (file.exists(script_path)) {
    # Create a Python command with the required arguments
    command <- sprintf(
      "import sys; sys.argv = ['%s', '-w', '%s', '-p', '%s', '-r', '%s', '-m', '%s', '-n', '%s', '-t', '%f', '-f', '%s']; exec(open('%s').read())", # nolint: line_length_linter.
      script_path, script_dir, profile_main_dir, profile_sub_dir, model_path, name_prefix, threshold, file_format, script_path # nolint: line_length_linter.
    )

    # Run the Python script with arguments
    reticulate::py_run_string(command)
  } else {
    stop("The specified script does not exist.")
  }
}